version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: handlebars
    versions:
    - "> 4.1.2"
  - dependency-name: npm
    versions:
    - 6.14.11
    - 6.14.12
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: all-contributors-cli
    versions:
    - 6.19.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
